"""The JSON Nix emits at build time. Generated by our own Nix from arguments
Nix has already validated, so it is not untrusted input."""

import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal, Mapping, Self, TypedDict

from launcher.lib.constants import ERROR_PREFIX


@dataclass(frozen=True, kw_only=True)
class ProxySpec:
    # Runs on the host and is the only policy point.
    sockd: Path
    # Runs inside the sandbox, translating HTTP proxy requests for sockd.
    privoxy: Path
    # The Nix-generated rule body; the launcher prepends the runtime header.
    dante_rules_file: Path

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Self:
        return cls(
            sockd=Path(data["sockd"]),
            privoxy=Path(data["privoxy"]),
            dante_rules_file=Path(data["dante_rules_file"]),
        )


@dataclass(frozen=True, kw_only=True)
class PortRange:
    first: int
    last: int

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Self:
        return cls(first=int(data["from"]), last=int(data["to"]))


@dataclass(frozen=True, kw_only=True)
class PublishedPort:
    port: int
    bind_addr: str

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Self:
        return cls(port=int(data["port"]), bind_addr=str(data["bind_addr"]))


def _get_nix(data: Mapping[str, Any]) -> Path | None:
    # Null unless the wrapper was built with allowNix: it is only ever used to
    # read the host's nix config, and there is no daemon to read it for.
    value = data["nix"]
    if value is None:
        return None
    return Path(value)


@dataclass(frozen=True, kw_only=True)
class DependenciesLinux:
    git: Path
    bwrap: Path
    pasta: Path
    nft: Path
    env: Path
    python: Path
    nix: Path | None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Self:
        git = Path(data["git"])
        bwrap = Path(data["bwrap"])
        pasta = Path(data["pasta"])
        nft = Path(data["nft"])
        env = Path(data["env"])
        python = Path(data["python"])
        nix = _get_nix(data)
        return cls(
            git=git,
            bwrap=bwrap,
            pasta=pasta,
            nft=nft,
            env=env,
            python=python,
            nix=nix,
        )


@dataclass(frozen=True, kw_only=True)
class DependenciesDarwin:
    git: Path
    nix: Path | None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Self:
        git = Path(data["git"])
        nix = _get_nix(data)
        return cls(git=git, nix=nix)


@dataclass(frozen=True, kw_only=True)
class SandboxBuildSpec:
    # The release of agent-sandbox.nix that built this wrapper, for triage. Read
    # by launch_log and by nothing that decides anything.
    version: str
    out_name: str
    sandbox_path: str  # $PATH not Path
    pkg_config_path: str
    allow_nix: bool
    allow_unix_sockets: bool
    # Unexpanded: "$HOME/.claude" is not a path yet. They become Path in
    # host_state.
    rw_dirs: tuple[str, ...]
    rw_files: tuple[str, ...]
    ro_dirs: tuple[str, ...]
    ro_files: tuple[str, ...]
    # Keys only. The values are shell expressions the stub resolves; they
    # never enter this process.
    env_keys: tuple[str, ...]
    # As declared, for launch.log; local_ports and proxy are what is enforced.
    allowed_endpoints: tuple[str, ...]
    # None means every host-local TCP port; the empty tuple means none.
    local_ports: tuple[PortRange, ...] | None
    published_ports: tuple[PublishedPort, ...]
    closure_paths_file: Path
    cacert_dir: Path
    cacert_bundle: Path
    shell: Path
    pre_entry_script: Path
    sandboxed_binary: Path
    proxy: ProxySpec | None


@dataclass(frozen=True, kw_only=True)
class SandboxBuildSpecLinux(SandboxBuildSpec):
    platform: Literal["linux"]
    hosts_file: Path
    empty_file: Path
    dependencies: DependenciesLinux


@dataclass(frozen=True, kw_only=True)
class SandboxBuildSpecDarwin(SandboxBuildSpec):
    platform: Literal["darwin"]
    dependencies: DependenciesDarwin


class _CommonBuildSpec(TypedDict):
    """The fields both platforms share, typed so `**` is checked by mypy."""

    version: str
    out_name: str
    sandbox_path: str
    pkg_config_path: str
    allow_nix: bool
    allow_unix_sockets: bool
    rw_dirs: tuple[str, ...]
    rw_files: tuple[str, ...]
    ro_dirs: tuple[str, ...]
    ro_files: tuple[str, ...]
    env_keys: tuple[str, ...]
    allowed_endpoints: tuple[str, ...]
    local_ports: tuple[PortRange, ...] | None
    published_ports: tuple[PublishedPort, ...]
    closure_paths_file: Path
    cacert_dir: Path
    cacert_bundle: Path
    shell: Path
    pre_entry_script: Path
    sandboxed_binary: Path
    proxy: ProxySpec | None


def _common_build_spec(data: Mapping[str, Any]) -> _CommonBuildSpec:
    ports = data["local_ports"]
    if ports is None:
        local_ports = None
    else:
        local_ports = tuple(PortRange.from_dict(entry) for entry in ports)

    published_ports = tuple(
        PublishedPort.from_dict(entry) for entry in data["published_ports"]
    )

    proxy_data = data.get("proxy")
    if proxy_data is None:
        proxy = None
    else:
        proxy = ProxySpec.from_dict(proxy_data)

    return _CommonBuildSpec(
        version=data["version"],
        out_name=data["out_name"],
        sandbox_path=data["sandbox_path"],
        pkg_config_path=data["pkg_config_path"],
        allow_nix=data["allow_nix"],
        allow_unix_sockets=data["allow_unix_sockets"],
        rw_dirs=tuple(data["rw_dirs"]),
        rw_files=tuple(data["rw_files"]),
        ro_dirs=tuple(data["ro_dirs"]),
        ro_files=tuple(data["ro_files"]),
        env_keys=tuple(data["env_keys"]),
        allowed_endpoints=tuple(data["allowed_endpoints"]),
        local_ports=local_ports,
        published_ports=published_ports,
        closure_paths_file=Path(data["closure_paths_file"]),
        cacert_dir=Path(data["cacert_dir"]),
        cacert_bundle=Path(data["cacert_bundle"]),
        shell=Path(data["shell"]),
        pre_entry_script=Path(data["pre_entry_script"]),
        sandboxed_binary=Path(data["sandboxed_binary"]),
        proxy=proxy,
    )


def load_build_spec(path: Path) -> SandboxBuildSpecLinux | SandboxBuildSpecDarwin:
    with path.open(encoding="utf-8") as handle:
        data: Mapping[str, Any] = json.load(handle)

    platform = data["platform"]
    if platform != sys.platform:
        raise SystemExit(
            f"{ERROR_PREFIX} {path}: built for {platform}, running on {sys.platform}"
        )

    common = _common_build_spec(data)
    dependencies_data = data["dependencies"]

    match platform:
        case "linux":
            return SandboxBuildSpecLinux(
                **common,
                platform="linux",
                hosts_file=Path(data["hosts_file"]),
                empty_file=Path(data["empty_file"]),
                dependencies=DependenciesLinux.from_dict(dependencies_data),
            )
        case "darwin":
            return SandboxBuildSpecDarwin(
                **common,
                platform="darwin",
                dependencies=DependenciesDarwin.from_dict(dependencies_data),
            )
        case _:
            # Reachable: platform comes from JSON, so the type checker
            # cannot exhaust it.
            raise SystemExit(f"{ERROR_PREFIX} {path}: unknown platform {platform!r}")
